project:
  type: website
  
resources:
  - "assets/*"

website:
  title: "Elissa Berwick"
  page-footer:
    left: "Made with [Quarto](https://quarto.org/)"
  navbar:
    pinned: true
    search: false
    right:
      - href: index.qmd
        text: Home
      - href: assets/berwick_cv0724.pdf
        text: CV
      - research.qmd
      - teaching.qmd


format:
  html:
    theme: 
      light: [journal, assets/fonts.scss, assets/styles-light.scss]
      dark: [journal, assets/fonts.scss, assets/styles-dark.scss]
    css: assets/styles.css
    toc: false
    page-layout: full

editor: visual

# setup help: https://ucsb-meds.github.io/creating-quarto-websites/